"""
Extended Pakistani Laws — 200+ additional sections
Covers: PPC (extended), CrPC, CPC, Family, Property, Labor, Tax, Cyber, Corporate
Append these to laws_engine.py LAWS_DATA list.
"""

EXTENDED_LAWS = [
    # ══════════════════════════════════════════════
    #  PPC — EXTENDED SECTIONS
    # ══════════════════════════════════════════════
    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"319","title":"Qatl-i-Khata (Culpable Homicide by Mistake)","text":"Whoever, without any intention to cause death or to cause such bodily injury as is likely to cause death, causes death of any person, is said to commit qatl-i-khata.","category":"Criminal","sub":"Homicide","keywords":["accidental death","qatl khata","mistake","no intention","accident","road accident","gaari se maut"],"punishment":"Diyat only","bailable":True,"severity":"Medium"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"337-A","title":"Itlaf-i-Udw (Amputation)","text":"Whoever commits Itlaf-i-udw, that is, causes loss of, or permanent damage to, any organ of the body of another person, shall be punished with Qisas, and if Qisas is not applicable, with imprisonment and diyat.","category":"Criminal","sub":"Bodily Harm","keywords":["amputation","organ loss","bodily harm","injury","grievous hurt","337A"],"punishment":"Qisas or Diyat + imprisonment","bailable":False,"severity":"High"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"337-L","title":"Punishment for Hurt","text":"Whoever causes hurt not amounting to grievous hurt shall be punished with imprisonment of either description for a term which may extend to one year, or with fine up to thirty thousand rupees, or with both.","category":"Criminal","sub":"Bodily Harm","keywords":["hurt","injury","zakhm","bodily harm","fighting","assault","maar","pitai"],"punishment":"Up to 1 year or Rs.30,000 fine","bailable":True,"severity":"Low"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"350","title":"Criminal Force","text":"Whoever intentionally uses force to any person, without that person's consent, in order to the committing of any offence, or intending by the use of such force to cause, or knowing it to be likely that by the use of such force he will cause, injury, fear or annoyance to the person to whom the force is used, is said to use criminal force to that other.","category":"Criminal","sub":"Assault","keywords":["criminal force","assault","attack","physical","force","harass","dhamki","maar"],"punishment":"Up to 3 months or fine","bailable":True,"severity":"Low"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"365-A","title":"Kidnapping for Ransom","text":"Whoever kidnaps or abducts any person with intent to hold such person for ransom shall be punished with death or imprisonment for life.","category":"Criminal","sub":"Kidnapping","keywords":["kidnapping","ransom","fidya","aghwa","365A","abduction ransom"],"punishment":"Death or Life imprisonment","bailable":False,"severity":"High"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"371","title":"Habitual Dealing in Slaves","text":"Whoever habitually imports, exports, removes, buys, sells, traffics, or deals in slaves, shall be punished with imprisonment for life, or with imprisonment of either description for a term not exceeding ten years, and shall also be liable to fine.","category":"Criminal","sub":"Human Trafficking","keywords":["slavery","trafficking","human trafficking","slave","child trafficking","labour trafficking"],"punishment":"Life or up to 10 years + fine","bailable":False,"severity":"High"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"375","title":"Rape — Definition","text":"A man is said to commit rape who has sexual intercourse with a woman under circumstances including: against her will; without her consent; with consent obtained by putting her in fear of death or hurt; or when she is unable to understand the nature and consequences of the act.","category":"Criminal","sub":"Sexual Violence","keywords":["rape","zina bil jabr","sexual assault","consent","375","women safety","without consent"],"punishment":"Death or 10-25 years + fine","bailable":False,"severity":"High"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"377","title":"Unnatural Offences","text":"Whoever voluntarily has carnal intercourse against the order of nature with any man, woman or animal, shall be punished with imprisonment for life, or with imprisonment of either description for a term which may extend to ten years, and shall also be liable to fine.","category":"Criminal","sub":"Sexual Offence","keywords":["377","unnatural","sexual offence"],"punishment":"Life or up to 10 years + fine","bailable":False,"severity":"High"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"380","title":"Theft in Dwelling House","text":"Whoever commits theft in any building, tent or vessel, which building, tent or vessel is used as a human dwelling, or for the custody of property, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.","category":"Criminal","sub":"Theft","keywords":["theft","ghar mein chori","house theft","dwelling theft","380","burglary","seendhna"],"punishment":"Up to 7 years + fine","bailable":False,"severity":"Medium"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"396","title":"Dacoity with Murder","text":"If any one of five or more persons who are conjointly committing dacoity, commits murder in so committing dacoity, every one of those persons shall be punished with death, or imprisonment for life, or rigorous imprisonment for a term which may extend to ten years, and shall also be liable to fine.","category":"Criminal","sub":"Robbery","keywords":["dacoity murder","daka qatl","396","gang murder","armed robbery murder"],"punishment":"Death or life or up to 10 years + fine","bailable":False,"severity":"High"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"405","title":"Criminal Breach of Trust — Definition","text":"Whoever, being in any manner entrusted with property, or with any dominion over property, dishonestly misappropriates or converts to his own use that property, or dishonestly uses or disposes of that property in violation of any direction of law prescribing the mode in which such trust is to be discharged, commits criminal breach of trust.","category":"Criminal","sub":"Fraud","keywords":["breach of trust","amanat khiyanat","misappropriate","embezzlement","trust violation","property misuse"],"punishment":"Up to 7 years + fine","bailable":False,"severity":"Medium"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"411","title":"Receiving Stolen Property","text":"Whoever dishonestly receives or retains any stolen property, knowing or having reason to believe the same to be stolen property, shall be punished with imprisonment of either description for a term which may extend to three years, or with fine, or with both.","category":"Criminal","sub":"Theft","keywords":["stolen property","receiving stolen","411","chori ka maal","handler"],"punishment":"Up to 3 years or fine or both","bailable":False,"severity":"Medium"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"417","title":"Punishment for Cheating","text":"Whoever cheats shall be punished with imprisonment of either description for a term which may extend to one year, or with fine, or with both.","category":"Criminal","sub":"Fraud","keywords":["cheating","fraud","dhoka","417","simple cheating","deception"],"punishment":"Up to 1 year or fine or both","bailable":True,"severity":"Low"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"463","title":"Forgery","text":"Whoever makes any false document or part of a document with intent to cause damage or injury to the public or to any person, or to support any claim or title, or to cause any person to part with property, or to enter into any express or implied contract, or with intent to commit fraud or that fraud may be committed, commits forgery.","category":"Criminal","sub":"Forgery","keywords":["forgery","jaali","fake document","false document","463","fraud document","jaali dastawez"],"punishment":"Up to 2 years or fine or both","bailable":True,"severity":"Medium"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"468","title":"Forgery for Purpose of Cheating","text":"Whoever commits forgery, intending that the document forged shall be used for the purpose of cheating, shall be punished with imprisonment of either description for a term which may extend to seven years, and shall also be liable to fine.","category":"Criminal","sub":"Forgery","keywords":["forgery","cheating","468","fake document fraud","jaali kagaz","cheque fraud","signature fake"],"punishment":"Up to 7 years + fine","bailable":False,"severity":"High"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"471","title":"Using Forged Document as Genuine","text":"Whoever fraudulently or dishonestly uses as genuine any document which he knows or has reason to believe to be a forged document, shall be punished in the same manner as if he had forged such document.","category":"Criminal","sub":"Forgery","keywords":["forged document","using fake","471","fake certificate","jaali certificate","degree fraud"],"punishment":"Same as forgery charge","bailable":False,"severity":"High"},

    {"act":"Pakistan Penal Code 1860","short":"PPC","sec":"489-F","title":"Dishonoured Cheque","text":"Whoever dishonestly issues a cheque towards repayment of a loan or fulfilment of an obligation which is dishonoured on presentation, shall be punished with imprisonment which may extend to three years, or with fine, or with both.","category":"Criminal","sub":"Fraud","keywords":["bounced cheque","dishonoured cheque","bad cheque","cheque bounce","489F","bank cheque","loan cheque"],"punishment":"Up to 3 years or fine or both","bailable":True,"severity":"Medium"},

    # ══════════════════════════════════════════════
    #  CODE OF CRIMINAL PROCEDURE 1898 (CrPC)
    # ══════════════════════════════════════════════
    {"act":"Code of Criminal Procedure 1898","short":"CrPC","sec":"22-A","title":"Justice of Peace — Powers","text":"A Justice of the Peace shall have powers to direct the police to register a criminal case if the police refuses to do so, and to give directions to maintain peace and order. Any person aggrieved by refusal of police to register FIR may apply to Justice of Peace.","category":"Criminal","sub":"Procedure","keywords":["justice of peace","22A","FIR refused","police refuse","register case","complaint","maqadma"],"punishment":None,"bailable":None,"severity":"High"},

    {"act":"Code of Criminal Procedure 1898","short":"CrPC","sec":"173","title":"Report by Police on Completion of Investigation","text":"Every investigation under this Chapter shall be completed without unnecessary delay, and, as soon as it is completed, the officer in charge of the police station shall submit a report through the prescribed channels.","category":"Criminal","sub":"Investigation","keywords":["police report","challan","investigation complete","173","police investigation","challan submit"],"punishment":None,"bailable":None,"severity":"Medium"},

    {"act":"Code of Criminal Procedure 1898","short":"CrPC","sec":"249-A","title":"Acquittal by Magistrate","text":"If, after taking the evidence for the prosecution and hearing the accused, a Magistrate considers that the evidence produced is not sufficient to justify a conviction, he may record an order of acquittal.","category":"Criminal","sub":"Trial","keywords":["acquittal","bari","249A","insufficient evidence","not guilty","case dismissed","case khatam"],"punishment":None,"bailable":None,"severity":"High"},

    {"act":"Code of Criminal Procedure 1898","short":"CrPC","sec":"265-K","title":"Acquittal by Session Court","text":"Nothing in this Chapter shall be deemed to prevent a Sessions Court from discharging or acquitting an accused at any stage of the trial if it considers the evidence produced to be insufficient to justify conviction.","category":"Criminal","sub":"Trial","keywords":["acquittal","session court","265K","discharge","insufficient evidence","bari"],"punishment":None,"bailable":None,"severity":"High"},

    {"act":"Code of Criminal Procedure 1898","short":"CrPC","sec":"436","title":"In What Cases Bail to be Taken","text":"When any person other than a person accused of a non-bailable offence is arrested or detained, he shall be released on bail. The person can give surety for his appearance.","category":"Criminal","sub":"Bail","keywords":["bail","zamaanat","436","bailable offence","release","surety","zamaandaar"],"punishment":None,"bailable":None,"severity":"High"},

    {"act":"Code of Criminal Procedure 1898","short":"CrPC","sec":"491","title":"Habeas Corpus","text":"Any High Court may, whenever it thinks fit, direct that a person be brought before the court and that the person be released if the court is satisfied that the person is detained without lawful authority.","category":"Criminal","sub":"Bail","keywords":["habeas corpus","illegal detention","491","unlawful custody","release","high court","writ"],"punishment":None,"bailable":None,"severity":"High"},

    # ══════════════════════════════════════════════
    #  CODE OF CIVIL PROCEDURE 1908 (CPC)
    # ══════════════════════════════════════════════
    {"act":"Code of Civil Procedure 1908","short":"CPC","sec":"9","title":"Courts to Try All Civil Suits","text":"The Courts shall have jurisdiction to try all suits of a civil nature except suits of which their cognizance is either expressly or impliedly barred.","category":"Civil","sub":"Jurisdiction","keywords":["civil suit","civil court","9","jurisdiction","civil case","dawa","mukadma"],"punishment":None,"bailable":None,"severity":"Medium"},

    {"act":"Code of Civil Procedure 1908","short":"CPC","sec":"20","title":"Where Suits to be Instituted","text":"Subject to the limitations aforesaid, every suit shall be instituted in a Court within the local limits of whose jurisdiction the defendant actually and voluntarily resides or carries on business or personally works for gain.","category":"Civil","sub":"Jurisdiction","keywords":["civil suit filing","where to file","jurisdiction","court venue","CPC 20","mukadma kahan daakhil karein"],"punishment":None,"bailable":None,"severity":"Medium"},

    {"act":"Code of Civil Procedure 1908","short":"CPC","sec":"80","title":"Notice Before Filing Suit Against Government","text":"Save in cases of urgency, no suit shall be instituted against the Government or against a public officer in respect of any act purporting to be done by such public officer in his official capacity, until two months have elapsed after notice has been delivered.","category":"Civil","sub":"Procedure","keywords":["notice government","80","government suit","two months notice","sarkari dawa","prior notice"],"punishment":None,"bailable":None,"severity":"Medium"},

    {"act":"Code of Civil Procedure 1908","short":"CPC","sec":"151","title":"Saving of Inherent Powers of Court","text":"Nothing in this Code shall be deemed to limit or otherwise affect the inherent power of the Court to make such orders as may be necessary for the ends of justice or to prevent abuse of the process of the Court.","category":"Civil","sub":"Procedure","keywords":["inherent powers","151","court powers","justice","abuse of process","stay order","injunction"],"punishment":None,"bailable":None,"severity":"Medium"},

    {"act":"Code of Civil Procedure 1908","short":"CPC","sec":"Order 39","title":"Temporary Injunction","text":"Where in any suit it is proved by affidavit or otherwise that any property in dispute is in danger of being wasted, damaged, or alienated by any party to the suit, the Court may grant a temporary injunction to restrain such act.","category":"Civil","sub":"Injunction","keywords":["injunction","stay order","temporary injunction","Order 39","property dispute","court order","roknay ka hukum"],"punishment":None,"bailable":None,"severity":"High"},

    # ══════════════════════════════════════════════
    #  SPECIFIC RELIEF ACT 1877
    # ══════════════════════════════════════════════
    {"act":"Specific Relief Act 1877","short":"SRA","sec":"8","title":"Recovery of Specific Immovable Property","text":"A person entitled to the possession of specific immovable property may recover it in the manner provided by the Code of Civil Procedure.","category":"Property","sub":"Recovery","keywords":["specific relief","immovable property","recovery","qabza wapsi","possession","property recovery","zameen wapis"],"punishment":None,"bailable":None,"severity":"High"},

    {"act":"Specific Relief Act 1877","short":"SRA","sec":"12","title":"Specific Performance of Contract","text":"Except as otherwise provided, the specific performance of any contract may, in the discretion of the court, be enforced when the act agreed to be done is in the performance of a trust, or when compensation in money would not be adequate relief.","category":"Civil","sub":"Contract","keywords":["specific performance","contract enforcement","mukammal adaigi","breach contract court","specific relief"],"punishment":None,"bailable":None,"severity":"Medium"},

    {"act":"Specific Relief Act 1877","short":"SRA","sec":"54","title":"Perpetual Injunction","text":"A perpetual injunction may be granted to prevent the breach of an obligation existing in favour of the applicant. Where the defendant is trustee of the property for the applicant, a perpetual injunction is appropriate.","category":"Civil","sub":"Injunction","keywords":["perpetual injunction","permanent injunction","court order","restraining order","SRA 54","property protection"],"punishment":None,"bailable":None,"severity":"High"},

    # ══════════════════════════════════════════════
    #  LIMITATION ACT 1908
    # ══════════════════════════════════════════════
    {"act":"Limitation Act 1908","short":"Limitation","sec":"3","title":"Bar of Limitation","text":"Subject to the provisions contained in sections 4 to 25, every suit instituted, appeal preferred, and application made after the period of limitation prescribed therefor by the First Schedule shall be dismissed.","category":"Civil","sub":"Limitation","keywords":["limitation","time limit","3 years","mukadma dakhil karne ki midat","barred by time","expired limitation"],"punishment":None,"bailable":None,"severity":"High"},

    {"act":"Limitation Act 1908","short":"Limitation","sec":"Art 113","title":"Limitation for Money Suit","text":"A suit for money based on a written contract must be filed within 6 years. A suit on open account must be filed within 3 years from the date when the account was stated.","category":"Civil","sub":"Limitation","keywords":["money suit","time limit","6 years","3 years","loan recovery","debt recovery","limitation money"],"punishment":None,"bailable":None,"severity":"Medium"},

    # ══════════════════════════════════════════════
    #  FAMILY LAWS — EXTENDED
    # ══════════════════════════════════════════════
    {"act":"Muslim Family Laws Ordinance 1961","short":"MFLO","sec":"Section 10","title":"Dower (Mehr)","text":"Where no details about the mode of payment of dower are specified in the nikah nama, the entire dower shall be presumed to be prompt. The wife can demand mehr before consummation of marriage.","category":"Family","sub":"Marriage","keywords":["mehr","dower","haq mehr","nikah","marriage payment","MFLO section 10","prompt mehr","deferred mehr"],"punishment":None,"bailable":None,"severity":"High"},

    {"act":"West Pakistan Muslim Personal Law (Shariat) Application Act 1962","short":"Shariat Act","sec":"2","title":"Application of Muslim Personal Law","text":"Notwithstanding any custom or usage, in all questions regarding succession, inheritance, legacies, wills, gifts, marriage, dower, divorce, maintenance, guardianship, and custody of children, the rule of decision shall be Muslim Personal Law.","category":"Family","sub":"Personal Law","keywords":["muslim personal law","shariat","inheritance","wirasat","marriage","divorce","maintenance","custody","family law"],"punishment":None,"bailable":None,"severity":"High"},

    {"act":"Guardian and Wards Act 1890","short":"GWA","sec":"Section 12","title":"Power to Make Interlocutory Order","text":"The Court may make such order for the temporary custody and protection of the person or property of the minor as it thinks proper pending the hearing of the application for appointment of a guardian.","category":"Family","sub":"Custody","keywords":["temporary custody","interim custody","child custody order","guardian ward","GWA 12","bachay ki taqseem"],"punishment":None,"bailable":None,"severity":"High"},

    {"act":"Guardian and Wards Act 1890","short":"GWA","sec":"Section 26","title":"Title of Mother to Custody","text":"The mother is entitled to custody of her minor child up to the age of 7 years for a boy and until puberty for a girl, unless the court considers it not to be in the welfare of the child.","category":"Family","sub":"Custody","keywords":["mother custody","hizanat","mother right","child age 7","girl custody","boy custody","GWA 26"],"punishment":None,"bailable":None,"severity":"High"},

    {"act":"Dowry and Bridal Gifts (Restriction) Act 1976","short":"Dowry Act","sec":"3","title":"Restriction on Dowry","text":"The total value of dowry, including all presents made at the time of or before or after marriage, shall not exceed five thousand rupees unless the parties are of the upper income group.","category":"Family","sub":"Marriage","keywords":["dowry","jahez","bridal gifts","dowry restriction","marriage gifts","jahez ka masla"],"punishment":"Up to 6 months + fine","bailable":True,"severity":"Medium"},

    {"act":"Child Marriage Restraint Act 1929","short":"CMRA","sec":"4","title":"Punishment for Male Adult Who Contracts Child Marriage","text":"Whoever, being a male above eighteen years of age, contracts a child marriage shall be punished with simple imprisonment which may extend to one month, or with fine which may extend to one thousand rupees, or with both.","category":"Family","sub":"Marriage","keywords":["child marriage","nababaligh shadi","underage marriage","CMRA","minor marriage","early marriage"],"punishment":"Up to 1 month or Rs.1000 fine","bailable":True,"severity":"Medium"},

    # ══════════════════════════════════════════════
    #  PROPERTY LAWS — EXTENDED
    # ══════════════════════════════════════════════
    {"act":"Transfer of Property Act 1882","short":"TPA","sec":"Section 53-A","title":"Part Performance","text":"Where any person contracts to transfer for consideration any immoveable property and the transferee has taken possession thereof in part performance of the contract, the transferor shall be debarred from enforcing against the transferee any right in respect of the property.","category":"Property","sub":"Sale","keywords":["part performance","possession","contract","53A","property possession","TPA","incomplete sale"],"punishment":None,"bailable":None,"severity":"High"},

    {"act":"Transfer of Property Act 1882","short":"TPA","sec":"Section 60","title":"Right of Mortgagor to Redeem","text":"At any time after the principal money has become due, the mortgagor has a right, on payment of the mortgage money, to require the mortgagee to deliver the mortgage deed and all documents relating to the mortgaged property.","category":"Property","sub":"Mortgage","keywords":["redemption","mortgage","rahn","right to redeem","girwi wapis","60 TPA","pay off mortgage"],"punishment":None,"bailable":None,"severity":"High"},

    {"act":"Transfer of Property Act 1882","short":"TPA","sec":"Section 108","title":"Rights and Liabilities of Lessor and Lessee","text":"In the absence of a contract or local usage to the contrary, the lessor and the lessee of immoveable property have the rights and are subject to the liabilities as stated in this section. Lessee must pay rent; lessor must maintain.","category":"Property","sub":"Lease","keywords":["landlord tenant rights","lessor lessee","108 TPA","rent rights","landlord duty","repair duty","kiraya dar haqooq"],"punishment":None,"bailable":None,"severity":"Medium"},

    {"act":"Stamp Act 1899","short":"Stamp Act","sec":"35","title":"Instruments Not Duly Stamped","text":"No instrument chargeable with duty shall be admitted in evidence for any purpose by any person having by law or consent of parties authority to receive evidence, unless such instrument is duly stamped.","category":"Property","sub":"Documentation","keywords":["stamp duty","stamp paper","35","unstamped document","registry","property document","stamp act"],"punishment":"Penalty up to 10x stamp duty","bailable":True,"severity":"Medium"},

    {"act":"Registration Act 1908","short":"Reg Act","sec":"17","title":"Documents of Which Registration is Compulsory","text":"The following documents shall be registered: instruments of gift of immoveable property; leases of immoveable property from year to year; non-testamentary instruments which purport or operate to create, declare, assign, limit or extinguish whether in present or in future any right in immoveable property of value of Rs.100 and upwards.","category":"Property","sub":"Registration","keywords":["registration","registry","17","compulsory registration","property registration","sale deed register","intiqal"],"punishment":"Document unenforceable if not registered","bailable":None,"severity":"High"},

    # ══════════════════════════════════════════════
    #  LABOR LAWS — EXTENDED
    # ══════════════════════════════════════════════
    {"act":"Factories Act 1934","short":"Factories Act","sec":"36","title":"Working Hours — Adults","text":"No adult worker shall be required or allowed to work in a factory for more than nine hours in any day and forty-eight hours in any week.","category":"Labor","sub":"Working Hours","keywords":["working hours","overtime","factory","9 hours","48 hours","overtime pay","kaam ke ghante","extra kaam"],"punishment":"Fine up to Rs.500","bailable":True,"severity":"Low"},

    {"act":"Factories Act 1934","short":"Factories Act","sec":"37","title":"Weekly Rest Day","text":"No adult worker shall be required or allowed to work in a factory on the first day of the week (Sunday) unless he has had or will have a holiday for a whole day on one of the three days immediately before or after that day.","category":"Labor","sub":"Working Hours","keywords":["weekly off","sunday off","rest day","holiday","factory worker","chutti","weekly holiday"],"punishment":"Fine","bailable":True,"severity":"Low"},

    {"act":"Minimum Wages Ordinance 1961","short":"Min Wages","sec":"4","title":"Minimum Wages","text":"The employer shall pay wages to every workman at a rate not less than the minimum rate of wages fixed. The Minimum Wage Board determines and revises minimum wages periodically.","category":"Labor","sub":"Wages","keywords":["minimum wage","kam se kam talab","wage board","salary minimum","minimum salary","worker pay","mazdoor talab"],"punishment":"Fine up to Rs.500 per violation","bailable":True,"severity":"Medium"},

    {"act":"Employees Social Security Ordinance 1965","short":"ESSO","sec":"18","title":"Employer Contribution","text":"Every employer shall pay contribution at the prescribed rate in respect of every insured person employed by him. The contribution goes to the Employees Social Security Institution for healthcare and benefits.","category":"Labor","sub":"Social Security","keywords":["ESSI","social security","employer contribution","health insurance","worker benefit","ESSO","PESSI","sarkari insurance"],"punishment":"Fine for non-compliance","bailable":True,"severity":"Medium"},

    {"act":"Employees Old Age Benefits Act 1976","short":"EOBI","sec":"9","title":"EOBI Contribution","text":"Every employer shall be liable to pay contribution at the prescribed rates to the institution in respect of each insured person in his employment. EOBI provides old age pension, invalidity pension and survivors pension.","category":"Labor","sub":"Pension","keywords":["EOBI","pension","old age","retirement benefit","employer contribution","employee pension","buzurg pension"],"punishment":"Fine + surcharge","bailable":True,"severity":"Medium"},

    {"act":"Workmen Compensation Act 1923","short":"WCA","sec":"3","title":"Employer Liability for Compensation","text":"If personal injury is caused to a workman by accident arising out of and in the course of his employment, his employer shall be liable to pay compensation. Includes injuries during work, occupational diseases.","category":"Labor","sub":"Compensation","keywords":["workmen compensation","accident","injury at work","employer liability","WCA","haadsa","kaam par zakhm","worker injury"],"punishment":"Employer pays compensation","bailable":None,"severity":"High"},

    # ══════════════════════════════════════════════
    #  NATIONAL ACCOUNTABILITY
    # ══════════════════════════════════════════════
    {"act":"National Accountability Bureau Ordinance 1999","short":"NAB","sec":"Section 10","title":"Holding Assets Beyond Means","text":"A person is guilty of corrupt practice if he is found to be in possession of pecuniary resources or property disproportionate to his known sources of income which he cannot reasonably account for.","category":"Criminal","sub":"Corruption","keywords":["assets beyond means","disproportionate assets","NAB","corruption","unexplained wealth","benami property","beyond income"],"punishment":"Up to 14 years + confiscation of assets","bailable":False,"severity":"High"},

    {"act":"National Accountability Bureau Ordinance 1999","short":"NAB","sec":"Section 15","title":"Plea Bargain","text":"At any time during the investigation or trial the accused may make an application to the Chairman NAB for voluntary return of the assets or gains acquired through corruption or corrupt practices.","category":"Criminal","sub":"Corruption","keywords":["plea bargain","voluntary return","NAB deal","corruption settlement","assets return"],"punishment":"Return assets + disqualification","bailable":None,"severity":"High"},

    # ══════════════════════════════════════════════
    #  CYBER CRIMES — EXTENDED
    # ══════════════════════════════════════════════
    {"act":"Prevention of Electronic Crimes Act 2016","short":"PECA","sec":"Section 3","title":"Unauthorized Access to Information System","text":"Whoever gains unauthorized access to any information system or data, shall be punished with imprisonment for a term which may extend to three months or with fine up to fifty thousand rupees or both.","category":"Criminal","sub":"Cyber Crime","keywords":["hacking","unauthorized access","PECA 3","computer crime","data breach","system access","password hack"],"punishment":"Up to 3 months or Rs.50,000 fine","bailable":True,"severity":"Low"},

    {"act":"Prevention of Electronic Crimes Act 2016","short":"PECA","sec":"Section 9","title":"Electronic Fraud","text":"Whoever with intent to deceive inputs, alters, deletes, or suppresses computer data resulting in unauthentic data for the purposes of being considered or acted upon for legal purposes as if it were authentic shall be punished with imprisonment up to two years or fine up to ten million rupees or both.","category":"Criminal","sub":"Cyber Crime","keywords":["electronic fraud","online fraud","cyber fraud","PECA 9","data alteration","internet scam","online dhoka"],"punishment":"Up to 2 years or Rs.10 million fine","bailable":False,"severity":"High"},

    {"act":"Prevention of Electronic Crimes Act 2016","short":"PECA","sec":"Section 24","title":"Cyber Terrorism","text":"Whoever commits any offence under this Act with the intent to coerce, intimidate or create terror in any government or any local authority, foreign government, or the general public shall be punished with imprisonment which may extend to fourteen years or with fine up to fifty million rupees or with both.","category":"Criminal","sub":"Terrorism","keywords":["cyber terrorism","PECA 24","online terror","digital threat","government system attack"],"punishment":"Up to 14 years or Rs.50 million fine","bailable":False,"severity":"High"},

    # ══════════════════════════════════════════════
    #  ANTI TERRORISM
    # ══════════════════════════════════════════════
    {"act":"Anti-Terrorism Act 1997","short":"ATA","sec":"6","title":"Terrorism — Definition","text":"Terrorism means the use or threat of action where the use or threat is designed to coerce and intimidate or overawe the Government or the public or a section of the public, create a sense of fear in the public, or advance a religious, sectarian or ethnic cause.","category":"Criminal","sub":"Terrorism","keywords":["terrorism","ATA","dhamaaka","blast","bomb","terror","sectarian","religious violence","danga"],"punishment":"Death to life imprisonment","bailable":False,"severity":"High"},

    {"act":"Anti-Terrorism Act 1997","short":"ATA","sec":"7","title":"Punishment for Terrorism","text":"Whoever commits an act of terrorism shall be punished with imprisonment of either description for a term which shall not be less than three years and may extend to imprisonment for life or with death.","category":"Criminal","sub":"Terrorism","keywords":["terrorism punishment","ATA 7","terrorist","bomb blast","armed attack"],"punishment":"3 years to death","bailable":False,"severity":"High"},

    # ══════════════════════════════════════════════
    #  COMPANIES ACT 2017
    # ══════════════════════════════════════════════
    {"act":"Companies Act 2017","short":"Companies Act","sec":"167","title":"Accounts and Audit","text":"Every company shall keep proper books of account and shall prepare and file annual audited accounts with the registrar within 30 days of the annual general meeting.","category":"Corporate","sub":"Accounts","keywords":["company accounts","audit","annual accounts","SECP filing","Companies Act 167","books of account","audit report"],"punishment":"Fine and imprisonment for directors","bailable":True,"severity":"Medium"},

    {"act":"Companies Act 2017","short":"Companies Act","sec":"204","title":"Liability of Directors","text":"A director shall not act on behalf of the company to promote his own interests. A director who acts in good faith, in the best interests of the company, and with proper care and diligence will not be liable for losses.","category":"Corporate","sub":"Directors","keywords":["director liability","company director","breach of duty","Companies Act 204","director responsibility","corporate governance"],"punishment":"Fine or imprisonment","bailable":True,"severity":"Medium"},

    # ══════════════════════════════════════════════
    #  INCOME TAX
    # ══════════════════════════════════════════════
    {"act":"Income Tax Ordinance 2001","short":"ITO","sec":"114","title":"Filing of Tax Return","text":"Every person whose taxable income in a tax year exceeds the maximum amount not chargeable to tax shall furnish a return of income for that year. Salaried persons, companies, associations of persons, and business owners are required to file annual returns.","category":"Tax","sub":"Income Tax","keywords":["income tax","tax return","filing","ITO","FBR","taxable income","return daakhil","tax jama","NTN"],"punishment":"Penalty + default surcharge","bailable":None,"severity":"Medium"},

    {"act":"Income Tax Ordinance 2001","short":"ITO","sec":"182","title":"Penalty for Non-Filing","text":"Any person who fails to furnish a return of income within the due date shall pay a penalty equal to 0.1% of the tax payable per day of default, subject to a minimum penalty of five thousand rupees.","category":"Tax","sub":"Income Tax","keywords":["tax penalty","late filing","ITO 182","FBR fine","non-filing penalty","return late"],"punishment":"0.1% per day + minimum Rs.5000","bailable":None,"severity":"Medium"},

    # ══════════════════════════════════════════════
    #  DRUG / NARCOTICS
    # ══════════════════════════════════════════════
    {"act":"Control of Narcotic Substances Act 1997","short":"CNSA","sec":"9","title":"Punishment for Drug Offences","text":"Whoever is found in possession of, or produces, processes, sells, purchases, transports, delivers, stores, exhibits, imports into or exports from Pakistan narcotic drugs or psychotropic substances shall be punished. Small quantity: 2 years. Large quantity: death or life imprisonment.","category":"Criminal","sub":"Narcotics","keywords":["drugs","narcotics","CNSA","charas","heroin","cocaine","drug possession","drug trafficking","nashe","manshiyat"],"punishment":"2 years to death depending on quantity","bailable":False,"severity":"High"},

    # ══════════════════════════════════════════════
    #  CONSUMER / BUSINESS
    # ══════════════════════════════════════════════
    {"act":"Competition Act 2010","short":"Competition","sec":"3","title":"Prohibited Agreements","text":"No undertaking or association of undertakings shall enter into any agreement or engage in any practice which has or is likely to have the effect of preventing, restricting or reducing competition.","category":"Consumer","sub":"Competition","keywords":["competition","monopoly","cartel","price fixing","Competition Act","SECP","market abuse","anti-competitive"],"punishment":"Fine up to 10% of annual turnover","bailable":None,"severity":"Medium"},

    {"act":"Punjab Consumer Protection Act 2005","short":"CPA Punjab","sec":"4","title":"Consumer Rights","text":"A consumer shall have the right to be protected against marketing of goods and services which are hazardous to life and property; to be informed about the quality, quantity, potency, purity, standard and price; and to seek redressal against unfair trade practices.","category":"Consumer","sub":"Consumer Rights","keywords":["consumer rights","Punjab CPA","defective goods","misleading","complaint","consumer court","kharab maal","saman wapis","refund"],"punishment":"Compensation + fine","bailable":None,"severity":"Medium"},
]
